EnableTLS: false
MaxUploadSize: 5000000000  #5Gb
DaysOld: 7 #max video age (deletion)
ServerPortTLS: 8086
ServerPort: 8085
CertPathCrt: "/etc/letsencrypt/live/xxxx/fullchain.pem"
CertPathKey: "/etc/letsencrypt/live/xxxx/privkey.pem"
BindtoAdress: "0.0.0.0" #use 127.0.0.1 to allow connection only from localhost
MaxVideosPerHour: 10
MaxVideoNameLen: 30
VideoResLow: 340  #resolution for Low quality video ex 360,480,720,1080
VideoResMed: 480  #resolution for Medium quality video ex 360,480,720,1080
VideoResHigh: 720 #resolution for High quality video ex 360,480,720,1080
CrfLow: 40  #crf value used in low conversion
CrfMed: 40  #crf value used in medium conversion
CrfHigh: 47 #crf value used in high conversion
EnableFDP: true #Enable file deletion after x day
EnablePHL: true #Enable upload limit per h
UploadPath: "./uploads"
ConvertPath: "./converted"
CheckOldEvery: "1h" #wait time before recheck  file deletion policies
AllowUploadWithPsw: false  #Allow upload only with password
Psw: "$2b$10$8SAg3.yBwKRQOniCGKBF0.pMJdEvJHmO5StRoekP0oVXNkG/aQ1q2" #password for video upload. Generate With "mkpasswd -m bcrypt -R 10 password"
