EnableTLS: false
EnableNoTLS: true
MaxUploadSize: 5000000000  #5Gb
DaysOld: 7 #max video age (deletion)
ServerPortTLS: 8086
ServerPort: 8085
CertPathCrt: "/etc/letsencrypt/live/xxxx/fullchain.pem"
CertPathKey: "/etc/letsencrypt/live/xxxx/privkey.pem"
BindtoAdress: "0.0.0.0" #use 127.0.0.1 to allow connection only from localhost
MaxVideosPerHour: 10
MaxVideoNameLen: 30
VideoResLow: 360  #resolution for Low quality video ex 360,480,720,1080
VideoResMed: 720  #resolution for Medium quality video ex 360,480,720,1080
VideoResHigh: 1080 #resolution for High quality video ex 360,480,720,1080
BitRateLow: 500k  #BitRate value used in low conversion
BitRateMed: 1500k  #BitRate value used in medium conversion
BitRateHigh: 3000k #BitRate value used in high conversion
EnableFDP: false #Enable file deletion after x day
EnablePHL: true #Enable upload limit per h
UploadPath: "./uploads"
ConvertPath: "./converted"
CheckOldEvery: "1h" #wait time before recheck  file deletion policies
AllowUploadOnlyFromUsers: true  #Allow upload only from users and admins
AllowUploadOnlyFromAdmins: false  #Allow upload only from users and admins
VideoOnlyForUsers: false #Show video and list only to users and admin
NrOfCoreVideoConv: "1" #Number of threads used for video conversion
DelVidAftUpl: true #Delete original video after conversion
VideoPerPage: 10 #Nr of displayed video per page in Video list
VideoConvPreset: "faster" #Options: ultrafast, superfast, veryfast, faster, fast, medium, slow, slower, veryslow
AllowEmbedded: true #Allow page for Embedding video in other page
